/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "FusionCRM DOCS",
  "tagline": "Dokumentáció és Tudásbázis",
  "favicon": "img/favicon.ico",
  "url": "https://hub.hellowp.io",
  "baseUrl": "/",
  "organizationName": "hellowpio",
  "projectName": "support.hellowp.io",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "hu",
    "locales": [
      "hu"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "docusaurus-plugin-sass",
    [
      "@docusaurus/plugin-google-tag-manager",
      {
        "containerId": "GTM-5TBMCF6"
      }
    ]
  ],
  "scripts": [
    {
      "src": "https://kit.fontawesome.com/11cbb0ec24.js",
      "crossorigin": "anonymous"
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/hellowpio/hub.hellowp.io/blob/main/",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/hellowpio/hub.hellowp.io/blob/main/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "algolia": {
      "appId": "I11ZQJ89FL",
      "apiKey": "6507f02646a676db1462458b97a1cda4",
      "indexName": "HelloWP HUB",
      "contextualSearch": false,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "image": "img/hellowp-hub.png",
    "navbar": {
      "title": "HelloWP Hub",
      "logo": {
        "alt": "HelloWP Hub",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "Termékek",
          "position": "left",
          "items": [
            {
              "label": "HelloPack",
              "to": "/docs/dokumentacio/hellopack"
            },
            {
              "label": "HelloTools",
              "to": "/docs/dokumentacio/hellotools"
            },
            {
              "label": "HelloIMG",
              "to": "/docs/dokumentacio/hellotools/helloimg"
            },
            {
              "label": "Üzemeltetés",
              "to": "/docs/dokumentacio/uzemeltetes-karbantartas"
            }
          ]
        },
        {
          "to": "docs/tudasbazis/",
          "label": "Tudásbázis",
          "position": "left"
        },
        {
          "to": "docs/sugo/",
          "label": "Súgó",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Közösség",
          "position": "left",
          "items": [
            {
              "label": "Discord",
              "to": "/docs/kozosseg/discord"
            },
            {
              "label": "Facebook",
              "to": "/docs/kozosseg/facebook"
            }
          ]
        },
        {
          "href": "https://hellowp.io/hu/helloconsole/",
          "label": "Console",
          "position": "right",
          "className": "header-console-link"
        },
        {
          "href": "https://github.com/hellowpio/hub.hellowp.io",
          "label": "GitHub",
          "position": "right",
          "className": "header-github-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "Termékek",
          "items": [
            {
              "label": "HelloPack",
              "to": "/docs/dokumentacio/hellopack"
            },
            {
              "label": "HelloTools",
              "to": "/docs/dokumentacio/hellotools"
            },
            {
              "label": "HelloIMG",
              "to": "/docs/dokumentacio/hellotools/helloimg"
            },
            {
              "label": "Üzemeltetés",
              "to": "/docs/dokumentacio/uzemeltetes-karbantartas"
            }
          ]
        },
        {
          "title": "Tudásbázis",
          "items": [
            {
              "label": "Oktatóanyagok",
              "to": "/docs/tudasbazis/oktatoanyagok"
            },
            {
              "label": "Hasznos eszközök",
              "to": "/docs/tudasbazis/hasznos-eszkozok"
            },
            {
              "label": "Hibaelhárítás",
              "to": "/docs/tudasbazis/hibaelharitas"
            },
            {
              "label": "Fejlesztői eszközök",
              "to": "/docs/tudasbazis/fejlesztoi-eszkozok"
            }
          ]
        },
        {
          "title": "Súgó",
          "items": [
            {
              "label": "Számlázás és előfizetés",
              "to": "/docs/sugo/szamlazas-es-elofizetesek"
            },
            {
              "label": "Partnerprogram",
              "to": "/docs/sugo/partnerprogram"
            },
            {
              "label": "Gyakori kérdések",
              "to": "/docs/sugo/egyeb"
            },
            {
              "label": "Hibakeresés és logolás",
              "to": "/docs/tudasbazis/hibaelharitas/wordpress/hibakereses-wordpress-ben"
            }
          ]
        },
        {
          "title": "Közösség",
          "items": [
            {
              "label": "Discord",
              "to": "/docs/kozosseg/discord"
            },
            {
              "label": "Facebook",
              "to": "/docs/kozosseg/facebook"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/hellowpio/hub.hellowp.io"
            }
          ]
        },
        {
          "title": "HelloWP",
          "items": [
            {
              "label": "Főoldal",
              "href": "https://hellowp.io"
            },
            {
              "label": "Console",
              "href": "https://hellowp.io/hu/helloconsole/"
            },
            {
              "label": "Kapcsolat",
              "href": "https://hellowp.io/hu/kapcsolat/"
            },
            {
              "label": "WordPress hírek",
              "href": "https://helloblog.io/hu/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "HelloWP!",
        "src": "img/logo-260-60-color.svg",
        "srcDark": "img/logo-260-60-wihte-green.svg",
        "href": "https://hellowp.io"
      },
      "copyright": "© 2026 TooEarlyBird, LLC <br> A forráskód <a href=\"/mit-licensz\">MIT</a>, a weboldal tartalma <a href=\"/cc-by-nc-sa-4.0\">CC BY NC SA 4.0 license</a> alatt áll.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "php",
        "css",
        "bash",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
